### ISSUE TITLE
老板 ，您的src 文件类是做了一个简单的封装吗？但是`use anerg\OAuth2\Util\Http;` 这个文件在哪里呢

### ISSUE THREAD

**Issue by m9rco** [anerg2046/sns_auth#1]
老板 ，您的src 文件类是做了一个简单的封装吗？但是`use anerg\OAuth2\Util\Http;` 这个文件在哪里呢

**Comment by m9rco** [comment]
我已经找到了，老板您写的非常好，fork了

**Comment by anerg2046** [comment]
通过composer安装，加载比较方便，不要直接下载，不然要改挺多地方
