### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certifica

### ISSUE THREAD

**Issue by Caesar0220** [anerg2046/sns_auth#20]
我在使用微信扫码登录的时候回调报错。网上查应该是GuzzleHttp证书的问题。请问在哪里关掉。

I used WeChat scan code to log in when I called back. Online checking should be the problem of GuzzleHttp certificate. Please tell me where to turn off.

**Comment by anerg2046** [comment]
我并不能复现你的问题，所以可能是你的配置问题

**Comment by griffin0220** [comment]
嗯。问题已经解决了。谢谢，你写的东西很好！

**Comment by Caesar0220** [comment]
> 我并不能复现你的问题，所以可能是你的配置问题

嗯。问题已经解决了。谢谢，你写的东西很好！

**Comment by anerg2046** [comment]
ok，那此问题关闭

**Comment by jay4497** [comment]
> > 我并不能复现你的问题，所以可能是你的配置问题
> 
> 嗯。问题已经解决了。谢谢，你写的东西很好！

请教下是怎么解决的呢？我也遇到相同问题，暂时改库代码给 guzzlehttp 请求加 `verify = false` 正常了，有不动库代码的方法么，传参数进去？

**Comment by jay4497** [comment]
@

> > 我并不能复现你的问题，所以可能是你的配置问题
> 
> 嗯。问题已经解决了。谢谢，你写的东西很好！

@liuzhaolun  请教下是怎么解决的呢？我也遇到相同问题，暂时改库代码给 guzzlehttp 请求加 verify = false 正常了，有不动库代码的方法么，传参数进去？

**Comment by anerg2046** [comment]
@jay4497 我猜的啊，应该是要升级主机的CA证书。我没遇到过这问题

**Comment by jay4497** [comment]
@anerg2046 主机CA证书？这个还真没注意过（的确之前是都正常，最近发现报这个错了），能给说说怎么升级么或给个相关链接也行，感谢！
