### ISSUE TITLE
老师请求下QQ那边的回调URL是这写么？

### ISSUE THREAD

**Issue by hulang** [anerg2046/sns_auth#22]
QQ那边的回调URL是这写么？
https://www.xxx.com/api/account/callback/name/qq.html
登录是：
https://www.xxx.com/api/account/login/name/qq.html

我的控制器是：Account 里面的代码完全复制您给出的。。

**Comment by anerg2046** [comment]
回调地址你自己可以试试啊，能访问到就行，回调地址自己想写哪儿都行

**Comment by hulang** [comment]
@anerg2046 谢谢老师了。

**Comment by hulang** [comment]
@anerg2046 能否加下我QQ指导下啊Q：939881475。。提示如下：
redirect uri is illegal(100010)

通知: QQ互联加强网站应用回调地址校验

点此报错      解决方案

**Comment by hulang** [comment]
已解决
