### ISSUE TITLE
获取新浪微博ACCESS_TOKEN出错：invalid_grant

### ISSUE THREAD

**Issue by surest-sky** [anerg2046/sns_auth#25]
关于如上问题，我是用过程中完全按照md格式的写法，除了修改回调地址外。 但是还是出现了这个问题。 不知道是我设置的哪些方面的原因呢。

**Comment by anerg2046** [comment]
确认一下你的回跳地址是否和微博开发者后台配置的一致，不一致就会有此问题

**Comment by ieliwb** [comment]
> 关于如上问题，我是用过程中完全按照md格式的写法，除了修改回调地址外。 但是还是出现了这个问题。 不知道是我设置的哪些方面的原因呢。



	/**
     * 构造函数
     *
     * @param array $config
     */
    public function __construct($config = null)
    {
        parent::__construct($config);
        $this->clientParams();
    }
    /**
     * 设置客户端请求的参数
     *
     * @return void
     */
    private function clientParams()
    {
        if (isset($this->config['access_token']) && !empty($this->config['access_token'])) {
            $this->token['access_token'] = $this->config['access_token'];
        }
        if (isset($this->config['uid']) && !empty($this->config['uid'])) {
            $this->token['openid'] = $this->config['uid'];
        }
    }




不知道是源码有bug还是什么问题，我改了就好了，自己处理下App登陆传过来的access_token和uid
