### ISSUE TITLE
您好，请问twitter登录的流程是什么

### ISSUE THREAD

**Issue by a731424344** [anerg2046/sns_auth#27]
您好，请问twitter登录的流程是什么，比如先获取token后获取userinfo这样 具体接口的参数我看了下好像和twitter开发者官网上不一样

**Comment by anerg2046** [comment]
浏览器登陆的话，所有的流程已经封装在sdk中，你不必关心怎么获取。
客户端app登录的话，需要使用官方的app sdk，然后将app获取到的oauth_token，oauth_token_secret，user_id，screen_name都传过来即可。

**Comment by a731424344** [comment]
我是后端，我拿到前端传来的oauth_token，oauth_token_secret，user_id，screen_name 再去请求1.1/users/show.json 就可以拿到头像昵称id之类的了吧

**Comment by a731424344** [comment]
您好，oauth_verifier是如何获取的，是前端调起url获取到oauth_verifier，然后再传给后端来的吗

**Comment by anerg2046** [comment]
你不关心这些
//你的配置
$config = [
'app_id'     => '3nHCxZgcK1WpYV**********',
'app_secret' => '2byVAPayMrG8LISjopwIMcJGy***************',
];
//前端传的
$config['oauth_token']        = $this->request->param('oauth_token', '');
$config['oauth_token_secret'] = $this->request->param('oauth_token_secret', '');
$config['user_id']            = $this->request->param('user_id', '');
$config['screen_name']        = $this->request->param('screen_name', '');
//直接拿用户信息
$snsInfo = OAuth::$platform($config)->userinfo();

**Comment by a731424344** [comment]
嗯，那就是前端执行了acesstoken的获取的这一步，后端直接拿到的就是访问令牌，可以访问twitter 的任何api
