### ISSUE TITLE
Fatal error: Class 'anerg\OAuth2\OAuth' not found

### ISSUE THREAD

**Issue by lyongdee** [anerg2046/sns_auth#28]
ThinkPHP 5.1 产生：
Fatal error: Class 'anerg\OAuth2\OAuth' not found

已经引入：
use think\facade\Config;
use anerg\OAuth2\OAuth;

**Comment by anerg2046** [comment]
检查下vendor目录下是不是有anerg2046/sns_auth目录，可能你的composer并没有下载成功

**Comment by lyongdee** [comment]
@anerg2046 有的，PHP Storm 里使用Ctrl+鼠标左键都已经跳到包内的代码了。

**Comment by lyongdee** [comment]
![image](https://user-images.githubusercontent.com/369124/58279649-8553a880-7dd1-11e9-930c-14a20aad18e0.png)

**Comment by lyongdee** [comment]
我在 application/api/controller 内引入包使用的。

`<?php
namespace app\api\controller;

use think\facade\Config;
use anerg\OAuth2\OAuth;

class Login extends Controller
{
    public function sns()
    {
        $platform = $this->request->param('sns_platform');
        // 获取本站的第三方登录配置
        $config = Config::get('sns.' . $platform);
        // $config['proxy'] = 'http://127.0.0.1:1080';
        // QQ、Facebook、Line 要求客户端传递 access_token 即可
        $config['access_token'] = $this->request->param('access_token', '');
        // Twitter 需要传递下面四个参数
        $config['oauth_token']        = $this->request->param('oauth_token', '');
        $config['oauth_token_secret'] = $this->request->param('oauth_token_secret', '');
        $config['user_id']            = $this->request->param('user_id', '');
        $config['screen_name']        = $this->request->param('screen_name', '');
        // 其他和 web 登录一样，要求客户端传递 code 过来即可，可以是 post 也可以是 get 方式

        $snsInfo = OAuth::$platform($config)->userinfo();
        print_r($snsInfo);
    }
}`

**Comment by anerg2046** [comment]
不知道你哪儿弄错了。
给个我自己的项目代码参考吧

```php
    /**
     * 第三方登录接口
     *
     * @param UserService $UserService
     * @return void
     */
    public function sns(UserService $UserService)
    {
        $this->validate($this->request->param(), 'app\common\validate\Member.AppSns');

        $platform = $this->request->param('sns_platform');

        if ($platform == 'google_ios') {
            //获取本站的第三方登录配置
            $config   = Config::get('google.' . Config::get('site.sns.' . $platform, ''));
            $platform = 'google';
        } else {
            //获取本站的第三方登录配置
            $config = Config::get($platform . '.' . Config::get('site.sns.' . $platform, ''));
        }

        // $config['proxy'] = 'http://127.0.0.1:1080';
        $config['access_token']       = $this->request->param('access_token', '');
        $config['oauth_token']        = $this->request->param('oauth_token', '');
        $config['oauth_token_secret'] = $this->request->param('oauth_token_secret', '');
        $config['user_id']            = $this->request->param('user_id', '');
        $config['screen_name']        = $this->request->param('screen_name', '');

        $snsInfo = OAuth::$platform($config)->userinfo();
        //app_id
        $snsInfo['app_id'] = isset($config['app_id']) ? $config['app_id'] : '';
        //使用第三方用户信息进行登录或注册操作
        $user = $UserService->snsLogin($snsInfo);

        return $this->outputJWT($user);
    }
```
