### ISSUE TITLE
移动端和PC扫码报错

### ISSUE THREAD

**Issue by kakuilan** [anerg2046/sns_auth#29]
使用的开发者账号,不是公众号

配置
return [
    'app_id'     => 'xxx',
    'app_secret' => 'xxx',
    'scope'      => 'snsapi_login',
];

- 移动端报[此公众号没有这些scope的权限,错误码10005]
- PC扫码报[获取微信 ACCESS_TOKEN 出错：{"errcode":40163,"errmsg":"code been used, hints: [ req_id: KjDCqZyFe-c8 ]"} ],打日志openid是获取到了的

**Comment by anerg2046** [comment]
账号必须是在mp.weixin.qq.com登陆后看到的
scope不要改，文档已经说的很清楚了
'scope'      => 'snsapi_userinfo',//如果需要静默授权，这里改成snsapi_base，**扫码登录系统会自动改为**snsapi_login

**Comment by kakuilan** [comment]
好的，谢谢
