### ISSUE TITLE
你好，我是使用composer安装，为什么还出现无法加载类库的错误

### ISSUE THREAD

**Issue by act2009** [anerg2046/sns_auth#34]
![image](https://user-images.githubusercontent.com/48006419/68752570-82c66300-063e-11ea-8e3e-ac63a9ed534e.png)

composer安装成功：

![image](https://user-images.githubusercontent.com/48006419/68752641-9f629b00-063e-11ea-9001-f6bfe118c86c.png)

![image](https://user-images.githubusercontent.com/48006419/68752718-bef9c380-063e-11ea-8cca-15254baab9fa.png)

在phpstrom里也可以Ctrl+左键成功跳转到OAuth：

![image](https://user-images.githubusercontent.com/48006419/68752847-f0728f00-063e-11ea-928a-ffe0de00b71d.png)

**Comment by anerg2046** [comment]
emm...你这个我还真不清楚。你的xdebug报错在40行，你的代码检查一下呢

**Comment by act2009** [comment]
> emm...你这个我还真不清楚。你的xdebug报错在40行，你的代码检查一下呢

代码是复制你的参考代码，不知道哪里有问题，如果下载到extend文件夹就没这个错误，就是比较麻烦，还会出现guzzlehttp类不存在错误，还要去下这个，所以最好还是使用composer安装

**Comment by act2009** [comment]
不知道什么原因，composer重装了下又好了 =。=, 感谢作者，真的特别方便~
