### ISSUE TITLE
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46'

### ISSUE THREAD

**Issue by baiwapak** [anerg2046/sns_auth#36]
调用 \GuzzleHttp\Client
$asciiHost = idn_to_ascii($uri->getHost(), $idnOptions, INTL_IDNA_VARIANT_UTS46, $info)
报错
Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46'

php版本是7.0.15。

**Comment by anerg2046** [comment]
composer update一下
