### ISSUE TITLE
你好，麻烦帮我看下报错是什么原因

### ISSUE THREAD

**Issue by mrainyo** [anerg2046/sns_auth#40]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install anerg2046/sns_auth v2.0.10
    - Conclusion: don't install anerg2046/sns_auth v2.0.8
    - Conclusion: don't install anerg2046/sns_auth v2.0.7
    - Conclusion: don't install anerg2046/sns_auth v2.0.6
    - Conclusion: don't install anerg2046/sns_auth v2.0.5
    - Conclusion: don't install anerg2046/sns_auth v2.0.4
    - Conclusion: don't install anerg2046/sns_auth v2.0.3
    - Conclusion: don't install anerg2046/sns_auth v2.0.2
    - Conclusion: don't install anerg2046/sns_auth v2.0.1
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Installation request for anerg2046/sns_auth ^2.0 -> satisfiable by anerg2046/sns_auth[v2.0.0, v2.0.1, v2.0.10, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8].
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - anerg2046/sns_auth v2.0.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.0.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by anerg2046** [comment]
升级一下你的composer，另外改一下阿里云的源

**Comment by mrainyo** [comment]
解决了 谢谢
