### ISSUE TITLE
可以升级一下guzzlehttp/guzzle包吗

### ISSUE THREAD

**Issue by lauyond** [anerg2046/sns_auth#47]
laravel新版已经是7.3了，直接require已经提示guzzle版本过低

**Comment by anerg2046** [comment]
你可以尝试使用dev版本，我刚更新了guzzle，如果没问题就进行合并

**Comment by anerg2046** [comment]
因为目前的工作很少涉及到sns登陆相关，而且大部分偏向golang的开发了，所以维护的比较少

**Comment by xgocn** [comment]
嗯，不过像guzzle这种依赖组件稍作升级还是对社区的巨大救济

**Comment by xgocn** [comment]
嗯，不过像guzzle这种依赖组件稍作升级还是对社区的巨大救济

**Comment by anerg2046** [comment]
> 嗯，不过像guzzle这种依赖组件稍作升级还是对社区的巨大救济

master已经升级了guzzle
