### ISSUE TITLE
Http类的init方法有问题

### ISSUE THREAD

**Issue by walker8** [anerg2046/sns_auth#5]
两个问题：
1、array_key_exists() expects parameter 2 to be array, null given
2、You must pass either an object or an array with the CURLOPT_HTTPHEADER argument
目前我暂时先把CURLOPT_HTTPHEADER这个设置去除了

**Comment by walker8** [comment]
我的测试环境是php7

**Comment by anerg2046** [comment]
助手类在更新的时候没注意，已修复
