### ISSUE TITLE
关于这个包的一点看法

### ISSUE THREAD

**Issue by lonycc** [anerg2046/sns_auth#8]
首先，感谢你的工作。其次，既然作为第三方依赖包，在代码里用cookie存储数据，感觉不妥。
有些场景，比如纯jwt提供接口服务，是无session/cookie维持状态的，不适用这个。

**Comment by anerg2046** [comment]
因为必然出现页面跳转的情况，这时候要传递url附加参数，所以cookie不可缺少。我不明白你的使用场景，这个包是不应该作为后端接口使用的
